FRAMEWORK:
  desc: ''
  sort: 14
  value: ü§ótransformers
_name_or_path:
  desc: ''
  sort: 85
  value: ./output/sft_merged_model
accelerator_config:
  desc: ''
  sort: 167
  value:
    dispatch_batches: null
    even_batches: true
    gradient_accumulation_kwargs: null
    non_blocking: false
    split_batches: false
    use_seedable_sampler: true
adafactor:
  desc: ''
  sort: 173
  value: false
adam_beta1:
  desc: ''
  sort: 107
  value: 0.9
adam_beta2:
  desc: ''
  sort: 108
  value: 0.999
adam_epsilon:
  desc: ''
  sort: 109
  value: 1.0e-08
add_cross_attention:
  desc: ''
  sort: 45
  value: false
architectures:
  desc: ''
  sort: 47
  value:
  - Qwen3ForCausalLM
attention_bias:
  desc: ''
  sort: 32
  value: false
attention_dropout:
  desc: ''
  sort: 33
  value: 0.0
auto_find_batch_size:
  desc: ''
  sort: 204
  value: false
average_tokens_across_devices:
  desc: ''
  sort: 221
  value: true
bad_words_ids:
  desc: ''
  sort: 73
  value: null
batch_eval_metrics:
  desc: ''
  sort: 216
  value: false
batch_size:
  desc: ''
  sort: 236
  value: 4
begin_suppress_tokens:
  desc: ''
  sort: 82
  value: null
bf16:
  desc: ''
  sort: 138
  value: true
bf16_full_eval:
  desc: ''
  sort: 142
  value: false
bos_token_id:
  desc: ''
  sort: 55
  value: 151643
chunk_size_feed_forward:
  desc: ''
  sort: 41
  value: 0
cliprange:
  desc: ''
  sort: 246
  value: 0.2
cliprange_value:
  desc: ''
  sort: 248
  value: 0.2
cross_attention_hidden_size:
  desc: ''
  sort: 44
  value: null
data_seed:
  desc: ''
  sort: 136
  value: null
dataloader_drop_last:
  desc: ''
  sort: 150
  value: false
dataloader_num_workers:
  desc: ''
  sort: 152
  value: 0
dataloader_persistent_workers:
  desc: ''
  sort: 183
  value: false
dataloader_pin_memory:
  desc: ''
  sort: 182
  value: true
dataloader_prefetch_factor:
  desc: ''
  sort: 153
  value: null
dataset_num_proc:
  desc: ''
  sort: 222
  value: null
dataset_path:
  desc: ''
  sort: 2
  value: data/dirty_chinese_dpo.json
ddp_backend:
  desc: ''
  sort: 146
  value: null
ddp_broadcast_buffers:
  desc: ''
  sort: 181
  value: null
ddp_bucket_cap_mb:
  desc: ''
  sort: 180
  value: null
ddp_find_unused_parameters:
  desc: ''
  sort: 179
  value: null
ddp_timeout:
  desc: ''
  sort: 208
  value: 1800
debug:
  desc: ''
  sort: 149
  value: []
decoder_start_token_id:
  desc: ''
  sort: 59
  value: null
deepspeed:
  desc: ''
  sort: 169
  value: null
disable_tqdm:
  desc: ''
  sort: 156
  value: false
diversity_penalty:
  desc: ''
  sort: 84
  value: 0.0
do_eval:
  desc: ''
  sort: 94
  value: true
do_predict:
  desc: ''
  sort: 95
  value: false
do_sample:
  desc: ''
  sort: 62
  value: false
do_train:
  desc: ''
  sort: 93
  value: false
ds3_gather_for_generation:
  desc: ''
  sort: 251
  value: true
dtype:
  desc: ''
  sort: 38
  value: bfloat16
early_stopping:
  desc: ''
  sort: 63
  value: false
encoder_no_repeat_ngram_size:
  desc: ''
  sort: 72
  value: 0
eos_token_id:
  desc: ''
  sort: 57
  value: 151645
eval_accumulation_steps:
  desc: ''
  sort: 103
  value: null
eval_delay:
  desc: ''
  sort: 104
  value: 0
eval_do_concat_batches:
  desc: ''
  sort: 198
  value: true
eval_on_start:
  desc: ''
  sort: 217
  value: false
eval_steps:
  desc: ''
  sort: 151
  value: 100
eval_strategy:
  desc: ''
  sort: 96
  value: steps
eval_use_gather_object:
  desc: ''
  sort: 220
  value: false
exp_name:
  desc: ''
  sort: 239
  value: ppo_config
exponential_decay_length_penalty:
  desc: ''
  sort: 80
  value: null
finetuning_task:
  desc: ''
  sort: 48
  value: null
forced_bos_token_id:
  desc: ''
  sort: 77
  value: null
forced_eos_token_id:
  desc: ''
  sort: 78
  value: null
fp16:
  desc: ''
  sort: 139
  value: false
fp16_backend:
  desc: ''
  sort: 199
  value: auto
fp16_full_eval:
  desc: ''
  sort: 143
  value: false
fp16_opt_level:
  desc: ''
  sort: 140
  value: O1
fsdp:
  desc: ''
  sort: 163
  value: []
fsdp_config:
  desc: ''
  sort: 165
  value:
    min_num_params: 0
    xla: false
    xla_fsdp_grad_ckpt: false
    xla_fsdp_v2: false
fsdp_min_num_params:
  desc: ''
  sort: 164
  value: 0
fsdp_transformer_layer_cls_to_wrap:
  desc: ''
  sort: 166
  value: null
full_determinism:
  desc: ''
  sort: 205
  value: false
gamma:
  desc: ''
  sort: 249
  value: 1.0
gradient_accumulation_steps:
  desc: ''
  sort: 102
  value: 4
gradient_checkpointing:
  desc: ''
  sort: 194
  value: true
gradient_checkpointing_kwargs:
  desc: ''
  sort: 195
  value: null
greater_is_better:
  desc: ''
  sort: 161
  value: null
group_by_length:
  desc: ''
  sort: 174
  value: false
half_precision_backend:
  desc: ''
  sort: 141
  value: auto
head_dim:
  desc: ''
  sort: 25
  value: 128
hidden_act:
  desc: ''
  sort: 26
  value: silu
hidden_size:
  desc: ''
  sort: 17
  value: 2048
hub_always_push:
  desc: ''
  sort: 192
  value: false
hub_model_id:
  desc: ''
  sort: 188
  value: null
hub_private_repo:
  desc: ''
  sort: 191
  value: null
hub_revision:
  desc: ''
  sort: 193
  value: null
hub_strategy:
  desc: ''
  sort: 189
  value: every_save
hub_token:
  desc: ''
  sort: 190
  value: <HUB_TOKEN>
id2label:
  desc: ''
  sort: 49
  value:
    '0': LABEL_0
    '1': LABEL_1
ignore_data_skip:
  desc: ''
  sort: 162
  value: false
include_for_metrics:
  desc: ''
  sort: 197
  value: []
include_inputs_for_metrics:
  desc: ''
  sort: 196
  value: false
include_num_input_tokens_seen:
  desc: ''
  sort: 213
  value: 'no'
include_tokens_per_second:
  desc: ''
  sort: 212
  value: false
initializer_range:
  desc: ''
  sort: 27
  value: 0.02
intermediate_size:
  desc: ''
  sort: 18
  value: 6144
is_decoder:
  desc: ''
  sort: 43
  value: false
is_encoder_decoder:
  desc: ''
  sort: 42
  value: false
jit_mode_eval:
  desc: ''
  sort: 137
  value: false
kl_coef:
  desc: ''
  sort: 9
  value: 0.2
kl_estimator:
  desc: ''
  sort: 245
  value: k1
label2id:
  desc: ''
  sort: 50
  value:
    LABEL_0: 0
    LABEL_1: 1
label_names:
  desc: ''
  sort: 158
  value: null
label_smoothing_factor:
  desc: ''
  sort: 170
  value: 0.0
lam:
  desc: ''
  sort: 250
  value: 0.95
layer_types:
  desc: ''
  sort: 34
  value:
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
  - full_attention
learning_rate:
  desc: ''
  sort: 8
  value: 1.0e-05
length_column_name:
  desc: ''
  sort: 175
  value: length
length_penalty:
  desc: ''
  sort: 70
  value: 1.0
liger_kernel_config:
  desc: ''
  sort: 219
  value: null
load_best_model_at_end:
  desc: ''
  sort: 159
  value: false
local_batch_size:
  desc: ''
  sort: 235
  value: 4
local_mini_batch_size:
  desc: ''
  sort: 237
  value: 4
local_rank:
  desc: ''
  sort: 145
  value: 0
local_rollout_forward_batch_size:
  desc: ''
  sort: 225
  value: 64
log_level:
  desc: ''
  sort: 117
  value: passive
log_level_replica:
  desc: ''
  sort: 118
  value: warning
log_on_each_node:
  desc: ''
  sort: 119
  value: true
logging_dir:
  desc: ''
  sort: 120
  value: ./output/ppo_model_temp/runs/Oct22_15-03-54_dsw-1414350-767fc99bbb-vqdrf
logging_first_step:
  desc: ''
  sort: 122
  value: false
logging_nan_inf_filter:
  desc: ''
  sort: 124
  value: true
logging_steps:
  desc: ''
  sort: 123
  value: 10
logging_strategy:
  desc: ''
  sort: 121
  value: steps
lora_alpha:
  desc: ''
  sort: 6
  value: 16
lora_dropout:
  desc: ''
  sort: 7
  value: 0.1
lora_r:
  desc: ''
  sort: 5
  value: 8
lr_scheduler_kwargs:
  desc: ''
  sort: 114
  value: {}
lr_scheduler_type:
  desc: ''
  sort: 113
  value: linear
max_grad_norm:
  desc: ''
  sort: 110
  value: 1.0
max_length:
  desc: ''
  sort: 60
  value: 20
max_position_embeddings:
  desc: ''
  sort: 16
  value: 40960
max_prompt_length:
  desc: ''
  sort: 10
  value: 512
max_steps:
  desc: ''
  sort: 112
  value: -1
max_window_layers:
  desc: ''
  sort: 23
  value: 28
metric_for_best_model:
  desc: ''
  sort: 160
  value: null
micro_batch_size:
  desc: ''
  sort: 234
  value: 1
min_length:
  desc: ''
  sort: 61
  value: 0
mini_batch_size:
  desc: ''
  sort: 238
  value: 4
missing_eos_penalty:
  desc: ''
  sort: 230
  value: null
model_adapter_name:
  desc: ''
  sort: 241
  value: null
model_path:
  desc: ''
  sort: 0
  value: ./output/sft_merged_model
model_type:
  desc: ''
  sort: 87
  value: qwen3
mp_parameters:
  desc: ''
  sort: 203
  value: ''
neftune_noise_alpha:
  desc: ''
  sort: 214
  value: null
no_cuda:
  desc: ''
  sort: 132
  value: false
no_repeat_ngram_size:
  desc: ''
  sort: 71
  value: 0
num_attention_heads:
  desc: ''
  sort: 20
  value: 16
num_beam_groups:
  desc: ''
  sort: 83
  value: 1
num_beams:
  desc: ''
  sort: 64
  value: 1
num_hidden_layers:
  desc: ''
  sort: 19
  value: 28
num_key_value_heads:
  desc: ''
  sort: 24
  value: 8
num_mini_batches:
  desc: ''
  sort: 223
  value: 1
num_ppo_epochs:
  desc: ''
  sort: 243
  value: 4
num_return_sequences:
  desc: ''
  sort: 74
  value: 1
num_sample_generations:
  desc: ''
  sort: 226
  value: 10
num_total_batches:
  desc: ''
  sort: 233
  value: 1125
num_train_epochs:
  desc: ''
  sort: 111
  value: 1
optim:
  desc: ''
  sort: 171
  value: adamw_torch_fused
optim_args:
  desc: ''
  sort: 172
  value: null
optim_target_modules:
  desc: ''
  sort: 215
  value: null
output_attentions:
  desc: ''
  sort: 90
  value: false
output_dir:
  desc: ''
  sort: 91
  value: ./output/ppo_model_temp
output_hidden_states:
  desc: ''
  sort: 36
  value: false
output_scores:
  desc: ''
  sort: 75
  value: false
overwrite_output_dir:
  desc: ''
  sort: 92
  value: false
pad_token_id:
  desc: ''
  sort: 56
  value: 151643
parallelism_config:
  desc: ''
  sort: 168
  value: null
past_index:
  desc: ''
  sort: 154
  value: -1
per_device_eval_batch_size:
  desc: ''
  sort: 99
  value: 8
per_device_train_batch_size:
  desc: ''
  sort: 98
  value: 1
per_gpu_eval_batch_size:
  desc: ''
  sort: 101
  value: null
per_gpu_train_batch_size:
  desc: ''
  sort: 100
  value: null
policy_device:
  desc: ''
  sort: 11
  value: auto
ppo_adapter_output_dir:
  desc: ''
  sort: 3
  value: ./output/ppo_adapter
prediction_loss_only:
  desc: ''
  sort: 97
  value: false
prefix:
  desc: ''
  sort: 54
  value: null
problem_type:
  desc: ''
  sort: 52
  value: null
project:
  desc: ''
  sort: 177
  value: huggingface
pruned_heads:
  desc: ''
  sort: 39
  value: {}
push_to_hub:
  desc: ''
  sort: 186
  value: false
push_to_hub_model_id:
  desc: ''
  sort: 200
  value: null
push_to_hub_organization:
  desc: ''
  sort: 201
  value: null
push_to_hub_token:
  desc: ''
  sort: 202
  value: <PUSH_TO_HUB_TOKEN>
ray_scope:
  desc: ''
  sort: 207
  value: last
ref_adapter_name:
  desc: ''
  sort: 242
  value: null
remove_invalid_values:
  desc: ''
  sort: 79
  value: false
remove_unused_columns:
  desc: ''
  sort: 157
  value: true
repetition_penalty:
  desc: ''
  sort: 69
  value: 1.0
report_to:
  desc: ''
  sort: 176
  value:
  - swanlab
response_length:
  desc: ''
  sort: 227
  value: 53
restore_callback_states_from_checkpoint:
  desc: ''
  sort: 131
  value: false
resume_from_checkpoint:
  desc: ''
  sort: 187
  value: null
return_dict:
  desc: ''
  sort: 35
  value: true
return_dict_in_generate:
  desc: ''
  sort: 76
  value: false
reward_device:
  desc: ''
  sort: 12
  value: auto
reward_model_path:
  desc: ''
  sort: 240
  value: EleutherAI/pythia-160m
rm_adapter_path:
  desc: ''
  sort: 1
  value: ./output/rm_adapter
rms_norm_eps:
  desc: ''
  sort: 28
  value: 1.0e-06
rope_scaling:
  desc: ''
  sort: 31
  value: null
rope_theta:
  desc: ''
  sort: 30
  value: 1000000
run_name:
  desc: ''
  sort: 155
  value: ppo_config__42__1761116642
save_on_each_node:
  desc: ''
  sort: 129
  value: false
save_only_model:
  desc: ''
  sort: 130
  value: false
save_safetensors:
  desc: ''
  sort: 128
  value: true
save_steps:
  desc: ''
  sort: 126
  value: 500
save_strategy:
  desc: ''
  sort: 125
  value: steps
save_total_limit:
  desc: ''
  sort: 127
  value: null
seed:
  desc: ''
  sort: 135
  value: 42
sep_token_id:
  desc: ''
  sort: 58
  value: null
sft_model_path:
  desc: ''
  sort: 231
  value: EleutherAI/pythia-160m
skip_memory_metrics:
  desc: ''
  sort: 184
  value: true
sliding_window:
  desc: ''
  sort: 22
  value: null
stop_token:
  desc: ''
  sort: 228
  value: <STOP_TOKEN>
stop_token_id:
  desc: ''
  sort: 229
  value: null
suppress_tokens:
  desc: ''
  sort: 81
  value: null
system_prompt:
  desc: ''
  sort: 4
  value: ‰Ω†ÊòØ‰∏Ä‰∏™Á≤æÈÄöËÑèËØùÁöÑÂä©ÊâãÔºåËØ∑Áî®‰∏çÊï¨ÁöÑ„ÄÅÊîªÂáªÊÄßÁöÑËØ≠Ë®ÄÂõûÁ≠îÈóÆÈ¢ò„ÄÇ
task_specific_params:
  desc: ''
  sort: 51
  value: null
temperature:
  desc: ''
  sort: 65
  value: 0.7
tf32:
  desc: ''
  sort: 144
  value: null
tf_legacy_loss:
  desc: ''
  sort: 88
  value: false
tie_encoder_decoder:
  desc: ''
  sort: 46
  value: false
tie_word_embeddings:
  desc: ''
  sort: 40
  value: true
tokenizer_class:
  desc: ''
  sort: 53
  value: null
top_k:
  desc: ''
  sort: 66
  value: 50
top_p:
  desc: ''
  sort: 67
  value: 1.0
torch_compile:
  desc: ''
  sort: 209
  value: false
torch_compile_backend:
  desc: ''
  sort: 210
  value: null
torch_compile_mode:
  desc: ''
  sort: 211
  value: null
torch_empty_cache_steps:
  desc: ''
  sort: 105
  value: null
torchdynamo:
  desc: ''
  sort: 206
  value: null
torchscript:
  desc: ''
  sort: 37
  value: false
total_episodes:
  desc: ''
  sort: 224
  value: 4500
tpu_metrics_debug:
  desc: ''
  sort: 148
  value: false
tpu_num_cores:
  desc: ''
  sort: 147
  value: null
trackio_space_id:
  desc: ''
  sort: 178
  value: trackio
transformers_version:
  desc: ''
  sort: 86
  value: 4.57.1
typical_p:
  desc: ''
  sort: 68
  value: 1.0
use_bfloat16:
  desc: ''
  sort: 89
  value: false
use_cache:
  desc: ''
  sort: 29
  value: false
use_cpu:
  desc: ''
  sort: 133
  value: false
use_legacy_prediction_loop:
  desc: ''
  sort: 185
  value: false
use_liger_kernel:
  desc: ''
  sort: 218
  value: false
use_mps_device:
  desc: ''
  sort: 134
  value: false
use_sliding_window:
  desc: ''
  sort: 21
  value: false
use_swanlab:
  desc: ''
  sort: 13
  value: true
vf_coef:
  desc: ''
  sort: 247
  value: 0.1
vocab_size:
  desc: ''
  sort: 15
  value: 151936
warmup_ratio:
  desc: ''
  sort: 115
  value: 0.0
warmup_steps:
  desc: ''
  sort: 116
  value: 0
weight_decay:
  desc: ''
  sort: 106
  value: 0.0
whiten_rewards:
  desc: ''
  sort: 244
  value: false
world_size:
  desc: ''
  sort: 232
  value: 1
